app/models/reservation.rb
db/migrate/20240528185316_create_reservations.rb
db/schema.rb
test/models/reservation_test.rb

created reservation model

---

app/models/kitchen.rb
db/migrate/20240528163943_create_kitchens.rb
test/models/kitchen_test.rb

Kitchen model created all associated columns. Awaiting review

kitchen model created

---

app/controllers/kitchens_controller.rb
test/controllers/kitchens_controller_test.rb

Kitchens controller

---

app/controllers/reservations_controller.rb
db/migrate/20240528193637_add_associations_kitchen.rb
test/controllers/reservations_controller_test.rb

@humayunk @VaedaSolomon @Jeffryaime if anyone is available to review

Create reservation controller

---

app/controllers/kitchens_controller.rb
app/views/kitchens/index.html.erb
db/schema.rb
test/controllers/kitchens_controller_test.rb

Index and View for the Kitchens.

Index and view

---

app/controllers/kitchens_controller.rb
app/views/kitchens/show.html.erb
db/schema.rb

please review controller and view

Kitchen show action

---

app/controllers/kitchens_controller.rb
app/views/kitchens/new.html.erb
config/routes.rb

completed kitchen create action and view. For review

Kitchen create action and view

---

app/controllers/kitchens_controller.rb
app/views/kitchens/my_kitchens.html.erb
config/routes.rb
db/schema.rb

I created the my-kitchens action and view along with the route for the owner.

My kitchens action and view

---

app/controllers/kitchens_controller.rb
app/views/kitchens/index.html.erb
app/views/kitchens/my_kitchens.html.erb
config/routes.rb

debugged mykitchens route to show all of owner's kitchens

debugged mykitchens route

---

app/controllers/reservations_controller.rb
app/views/kitchens/show.html.erb

- Hitting "create reservation" now creates reservation
- Added font-awesome to replace booleans

updating reservation controller and minor styling

---

app/controllers/reservations_controller.rb
app/views/kitchens/my_kitchens.html.erb

Partially coded actions and view for owners kitchens and owners reservations

partially completed owner reservations

---

app/javascript/application.js
app/views/kitchens/my_kitchens.html.erb

my_kitchens reservations table populated. For review

input fields in reservations table working

---

app/views/kitchens/show.html.erb

need to check later if still have issues

added $ sign on total price but js seems to work

---

app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

This PR includes: 
1. create listing button in nav now has proper formating
2. CSS for nav and home in proper partials
3. Links for logged in nav drop down redirects to my kitchens and my reservations

refactored nav css 

---

app/views/kitchens/show.html.erb

To test this pr: 
1) Create a new kitchen
2) attach and image
3) See if it shows in the show page
Thanks.

tested image upload and showed a photo on show page

---

app/models/kitchen.rb

validations for kitchen model

---

app/controllers/reservations_controller.rb
app/views/reservations/index.html.erb

my reservations updated to show only outgoing reservations

---

Gemfile
Gemfile.lock
app/controllers/kitchens_controller.rb
app/models/kitchen.rb
app/views/kitchens/index.html.erb

will do design on another branch

did the logic part of search bar

---

app/views/kitchens/my_kitchens.html.erb

style updates for my kitchen page

---

app/controllers/kitchens_controller.rb
app/controllers/reviews_controller.rb
app/models/kitchen.rb
app/models/review.rb
app/models/user.rb
app/views/kitchens/show.html.erb
config/routes.rb
db/migrate/20240531163401_create_reviews.rb
db/schema.rb
db/seeds.rb
test/controllers/reviews_controller_test.rb
test/models/review_test.rb

Show reviews kitchen show
